#!/usr/bin/env python
""" Command Line Interface for W24
"""
import argparse
import asyncio

import werk24.cli.techread

# parse the args
parser = argparse.ArgumentParser(prog="w24cli")
subparsers = parser.add_subparsers(
    dest="command")

parser_techread = subparsers.add_parser(
    "techread",
    help="Submit a Technical Drawing to Werk24 for analysis")

parser_techread.add_argument(
    "input_file",
    help="path to the file that is to be analyzed")

parser_techread.add_argument(
    "-i",
    "--ignore-architecture-status",
    help="flag indicating whether the architecture status should be ignored(i.e. whether the request should be sent even though the architecture is unavailable)",
    action="store_true")

parser_techread.add_argument(
    "--ask-techread-started",
    help="ask for a callback when the techread process has been picked up by a worker",
    action="store_true")

parser_techread.add_argument(
    "--ask-page-thumbnail",
    help="ask for a thumbnail for each page in the document",
    action="store_true")

parser_techread.add_argument(
    "--ask-sheet-thumbnail",
    help="ask for a thumbnail of each sheet in the document",
    action="store_true")

parser_techread.add_argument(
    "--ask-plane-thumbnail",
    help="ask for a thumbnail of each plane of each sheet in the document",
    action="store_true")

parser_techread.add_argument(
    "--ask-variant-overall-dimensions",
    help="ask for the overall dimensions of each variant. The API will return the x,y,z dimensions as well as an enum indicating the shape",
    action="store_true")

parser_techread.add_argument(
    "--ask-train",
    help="ask the the API to use the document solely for training. This is mainly used for internal purposes, but your are invited to submit additional files if you want to help us improve our system. Your will not be charged for these requests (but you'll also not get a response)",
    action="store_true")

if __name__ == "__main__":

    args = parser.parse_args()
    if args.command == "techread":
        asyncio.run(werk24.cli.techread.main(args))
