import argparse

from werk24.cli import utils
from werk24.techread_client import W24TechreadClient
from werk24.models.helpdesk import W24HelpdeskTask


async def main(
    args: argparse.Namespace
) -> None:
    """
    Interact with the helpdesk client through the API

    Args:
        args(argparse.Namespace): CLI args generated by
        argparse
    """
    if args.command == "create-helpdesk-task":
        await _handle_create_helpdesk_task(args)


async def _handle_create_helpdesk_task(args: argparse.Namespace) -> None:

    # create the task
    print("called", args)
    task = W24HelpdeskTask(
        request_id=args.request_id,
        observed_outcome=args.observed_outcome,
        expected_outcome=args.expected_outcome,
        comment=args.comment,
        position=None,
        importance=args.importance
    )

    # get the client instance and handle
    # potential errors
    client = utils.make_client()
    async with client as session:
        await session.create_helpdesk_task(task)
