name: Tests | cpython 3.9, 3.10, 3.11, 3.12

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.9, 3.10.x, 3.11.x, 3.12.x]
        python-version: [3.12.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nose2
        run: pip install nose2

      - name: Install Dependencies
        run: python -m pip install -r ./requirements.txt && python -m pip install -r ./test/requirements.txt

      - name: Test
        env:
          W24TECHREAD_AUTH_REGION: ${{ secrets.W24TECHREAD_AUTH_REGION }}
          W24TECHREAD_AUTH_TOKEN: ${{ secrets.W24TECHREAD_AUTH_TOKEN }}
        run: nose2

      - name: Checkout the json schema
        uses: actions/checkout@v4
        with:
          repository: W24-Service-GmbH/werk24-json-schema
          ref: main
          path: werk24-json-schema
          token: ${{ secrets.JSON_SCHEMA_GITHUB_PATS_TOKEN }}

      - name: Create the json schema
        run: python -m  utils.create_json_schema ./werk24-json-schema/werk24-json-schema.json

      - name: Push the json schema to main
        run : |
            cd werk24-json-schema
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Add release notes for new release"
            git push

      - name: Create release in the second repository
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.JSON_SCHEMA_GITHUB_PATS_TOKEN }}
        with:
          # tag_name: ${{ github.event.release.tag_name }}
          # release_name: Release ${{ github.event.release.tag_name }}
          tag_name: v0.0.0
          release_name: Release v0.0.0
          body: Read the Release Notes of the werk24-python for details.
          draft: true
          prerelease: true
